server {
    listen 80;
    server_name <YOUR_DOMAIN>;
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
         # Personal Wiki 静态站点配置
        root /var/www/<YOUR_USER>/html;
        index index.html;
        try_files $uri $uri.html $uri/ =404;
    }
    
}
